# Generated by Django 4.2.4 on 2023-09-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0019_alter_category_category_illustration'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='days_of_week',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='months',
            field=models.CharField(blank=True, choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
