# Generated by Django 4.2.4 on 2023-11-06 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0023_alter_dayofweek_name_alter_month_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='months',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='offerdate',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='offerdate',
            name='offer_id',
        ),
        migrations.RemoveField(
            model_name='offerdate',
            name='startdate',
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_dates',
            field=models.ManyToManyField(default=None, null=True, to='offers.offerdate'),
        ),
        migrations.AddField(
            model_name='offerdate',
            name='day',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='offers.dayofweek'),
        ),
        migrations.AddField(
            model_name='offerdate',
            name='end_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='offerdate',
            name='month',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='offers.month'),
        ),
        migrations.AddField(
            model_name='offerdate',
            name='start_date',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
