# Generated by Django 4.2.4 on 2023-11-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0024_remove_offer_days_of_week_remove_offer_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdate',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='offerdate',
            name='start_date',
        ),
        migrations.AddField(
            model_name='offerdate',
            name='end_time',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='offerdate',
            name='start_time',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_dates',
            field=models.ManyToManyField(default=None, to='offers.offerdate'),
        ),
    ]
