# Generated by Django 4.2.3 on 2024-11-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0026_remove_offer_offer_dates_offerdate_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
