# Generated by Django 4.2.4 on 2023-09-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='offer_id',
            new_name='offer',
        ),
    ]
